### PR TITLE
Fix position overwrite for ready position with selected character

### LINKED ISSUE #563: 2p vs net selection does not move cursor to ready
on beta
Noticed this while playing around with the merge for #550 
The first selection of a button essentially "marks" that button as the button to return to when selecting a character somehow.
Reoccurs every time after returning to select screen.

### PR DESCRIPTION
**Pull request by Endaris**
Fixes #563, initial sending of the menu state upon entering the room caused overwriting of the __Ready id on the map with the coordinate of the selected character because it was missing a shallowcpy.

### CODE REVIEW

File: select_screen/select_screen.lua [hunk 1]
```diff
@@ -489,7 +489,7 @@ function select_screen.initializeFromMenuState(self, playerNumber, menuState)
   self.players[playerNumber].wants_ready = menuState.wants_ready or false
   self.players[playerNumber].ranked = menuState.ranked
   self.players[playerNumber].cursor.positionId = menuState.cursor
-  self.players[playerNumber].cursor.position = self.name_to_xy_per_page[self.current_page][menuState.cursor]
+  self.players[playerNumber].cursor.position = self.name_to_xy_per_page[self.current_page][menuState.cursor] and shallowcpy(self.name_to_xy_per_page[self.current_page][menuState.cursor]) or nil
```
Comment (JamesVanBoxtel) [inline select_screen/select_screen.lua:492]: We should probably just make shallowcpy return nil if nil is passed in. That would simplify cases like this and seems sensible

Comment (Endaris) [reply select_screen/select_screen.lua]: Yeah, no real reason not to. Done!

**Review by JamesVanBoxtel — APPROVED** [review]

**Review by Shosoul — APPROVED** [review]
