### PR TITLE
Changes to rating display to use the highest rating

### LINKED ISSUE #307: Player rating shown in lobby can be wrong if duplicate usernames on leaderboard
Probably should just use the higher number for now until we have accurate info from the server

### PR DESCRIPTION
**Pull request by Shosoul**
The rating display now will use the highest rating matched to an username instead of the lowest.

### CODE REVIEW

**Comment by Shosoul** [comment]
As mentioned by @JamesVanBoxtel in #307, this is a band-aid fix until we get the server to actually send ratings.

File: mainloop.lua [hunk 1]
```diff
@@ -628,7 +628,11 @@ function main_net_vs_lobby()
           lobby_menu:show_controls(true)
         end
         leaderboard_report = msg.leaderboard_report
-        for k, v in ipairs(leaderboard_report) do
+        local rev_leaderboard_report = {}
```
Comment (JamesVanBoxtel) [inline mainloop.lua:631]: Rather than make a whole new table lets just reverse enumerate

https://stackoverflow.com/questions/41349526/how-to-iterate-lua-table-from-end
